# Generated by Django 5.0 on 2025-08-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('informacoes', models.TextField()),
                ('endereco', models.CharField(max_length=200)),
                ('turno', models.CharField(blank=True, help_text='Digite manhã, tarde ou noite', max_length=8, null=True)),
                ('duracao', models.TimeField(blank=True, help_text='Use este formato: HH:MM', null=True)),
                ('ingresso', models.BooleanField(help_text='Digite V ou F')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, help_text='Digite o valor da atração em R$', max_digits=10, verbose_name='Preço')),
                ('guia', models.BooleanField(help_text='Digite V ou F')),
                ('participantes', models.IntegerField(help_text='Digite a quantidade de participantes mínima para a atividade')),
                ('nota', models.FloatField(default=0.0, help_text='Digite uma nota de 0 a 5')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
