# Generated by Django 5.0 on 2025-08-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Informe o título para a avaliação', max_length=100, verbose_name='Título')),
                ('data_avaliacao', models.DateField()),
                ('data_visita', models.DateField()),
                ('comentario', models.TextField(help_text='Escreva seu comentário', verbose_name='Comentário')),
                ('nota', models.IntegerField(default=0.0, help_text='Digite uma nota de 0 a 5')),
                ('acompanhantes', models.CharField(help_text='Digite entre: familia, amigos, romantico, a sos', max_length=20)),
                ('likes', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do local', max_length=100)),
                ('informacoes', models.TextField(help_text='Digite as informações relevântes sobre o local', verbose_name='Informações')),
                ('endereco', models.CharField(help_text='Digite: Nome da rua, número, bairro, cidade', max_length=200)),
                ('horario_abertura', models.TimeField(help_text='Use este formato: HH:MM', verbose_name='Horário de abertura')),
                ('horario_fechamento', models.TimeField(help_text='Use este formato: HH:MM', verbose_name='Horário de fechamento')),
                ('ingresso', models.BooleanField(help_text='Digite V ou F')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Digite o valor do ingresso em R$', max_digits=10, null=True)),
                ('acessibilidade', models.BooleanField()),
                ('classificacao_idade', models.IntegerField(help_text='Digite a idade mínima permitida para o local')),
                ('contato', models.EmailField(help_text='Informe o email de contato do local', max_length=254)),
                ('nota', models.FloatField(default=0.0, help_text='Digite uma nota de 0 a 5', verbose_name='Classificação de idade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(help_text='Cidade que reside', max_length=255)),
                ('pais', models.CharField(help_text='Pais que reside', max_length=60, verbose_name='País')),
                ('bio', models.CharField(help_text='Biografia sobre você para o seu perfil', max_length=255, verbose_name='Biografia')),
                ('passaporte', models.CharField(help_text='Digite o número do seu passaporte', max_length=10, verbose_name='Número do passaporte')),
                ('data_nascimento', models.DateField(help_text='Use o formato: ', verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro'), ('nao especificado', 'Não e especificado')], default='nao especificado', max_length=20, verbose_name='Gênero')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
