# Generated by Django 5.0 on 2025-08-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_avaliacao_local_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('status_moderacao', models.CharField(choices=[('excluida', 'Excluída')], default='excluida', max_length=40, verbose_name='Status de moderação')),
                ('status', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporte', models.CharField(choices=[('carro', 'Carro'), ('motocicleta', 'Motocicleta'), ('onibus', 'Ônibus'), ('trem', 'Trem'), ('metro', 'Metrô'), ('aviao', 'Avião'), ('barco', 'Barco'), ('caminhando', 'Caminhando'), ('bicicleta', 'Bicicleta'), ('outro', 'Outro')], default='outro', help_text='Selecione o tipo de transporte que você usará até o destino da viagem', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='atividade',
            name='duracao',
            field=models.TimeField(blank=True, help_text='Duração média da atividade\nUse este formato: HH:MM', null=True, verbose_name='Duração da atividade'),
        ),
        migrations.AlterField(
            model_name='local',
            name='classificacao_idade',
            field=models.IntegerField(help_text='Digite a idade mínima permitida para o local', verbose_name='Classificação de idade'),
        ),
        migrations.AlterField(
            model_name='local',
            name='nota',
            field=models.FloatField(default=0.0, help_text='Digite uma nota de 0 a 5'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro'), ('nao especificado', 'Não especificado')], default='nao especificado', max_length=20, verbose_name='Gênero'),
        ),
    ]
