# Generated by Django 5.0 on 2025-09-03 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0003_pergunta_viagem_alter_atividade_duracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='guia',
            field=models.BooleanField(help_text='Marque se a atividade possuir guia'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='ingresso',
            field=models.BooleanField(help_text='Marque se houver ingresso pago'),
        ),
        migrations.AlterField(
            model_name='local',
            name='ingresso',
            field=models.BooleanField(help_text='marque se houver ingresso pago'),
        ),
        migrations.AlterField(
            model_name='local',
            name='nota',
            field=models.FloatField(default=0.0, help_text='Digite uma nota de 0 a 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
