# Generated by Django 5.0 on 2025-09-10 13:37

import django.core.validators
import relacionamento.validators.validadorcpf
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), relacionamento.validators.validadorcpf.valida_cpf], verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
