# Generated by Django 5.0 on 2025-09-10 14:02

import django.core.validators
import relacionamento.validators.validadorcpf
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do reporter', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Reporter')),
                ('cpf', models.CharField(help_text='Insira o CPF sem pontos', max_length=11, validators=[django.core.validators.MinLengthValidator(11), relacionamento.validators.validadorcpf.valida_cpf], verbose_name='CPF')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
