# Generated by Django 5.0 on 2025-09-10 14:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamento', '0002_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Revista', max_length=100)),
                ('edicao', models.CharField(help_text='Edição(numérico) da Revista', max_length=100, verbose_name='Edição da revista')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Insira o título do artigo.', max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Título')),
                ('data_publicacao', models.DateField(verbose_name='Data publicação')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamento.reporter')),
                ('revistas', models.ManyToManyField(to='relacionamento.revista')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
