# Generated by Django 5.1.3 on 2025-09-11 12:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamento', '0003_revista_artigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Insira o título do artigo.', max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Título')),
                ('data_publicacao', models.DateField(verbose_name='Data publicação')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamento.reporter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('observacao', models.TextField()),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamento.pessoa')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamento.paper')),
                ('revista', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamento.revista')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='revistas',
            field=models.ManyToManyField(blank=True, null=True, through='relacionamento.Publicacao', to='relacionamento.revista'),
        ),
    ]
