# Generated by Django 5.0 on 2025-10-22 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamento', '0004_paper_publicacao_paper_revistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionamento.reporter'),
        ),
    ]
