# Generated by Django 5.0 on 2025-11-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamento', '0005_alter_paper_reporter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporter',
            options={'permissions': [('generate_name_reporter', 'Can generate name')]},
        ),
    ]
